name: bank_sathi
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 3.0.4+40

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^2.1.0
  pin_code_fields: ^7.0.0
  get: ^4.3.8
  android_intent: ^2.0.2
  shared_preferences: ^2.0.3
  flutter_screenutil: ^5.0.0+2
  flutter_svg: ^0.22.0
  cupertino_icons: ^1.0.0
  masked_text: ^0.0.6
  infinite_carousel: ^1.0.1
  carousel_slider: ^4.0.0
  mask_text_input_formatter: ^2.0.0
  image_picker: ^0.8.1+3
  image_cropper: ^1.3.1
  flutter_typeahead: ^3.1.3
  retrofit: any
  showcaseview: ^1.1.2
  firebase_messaging: ^10.0.0
  firebase_core: ^1.2.0
  flutter_local_notifications: ^6.0.0
  firebase_messaging_platform_interface: ^3.0.0
  firebase_dynamic_links: ^2.0.4
  share: ^0.6.5+4
  truecaller_sdk: ^0.0.3
  data_connection_checker: ^0.3.4
  url_launcher: ^6.0.4
  package_info: ^0.4.0+13
  exif: ^2.2.0
  path_provider: ^2.0.1
  image: ^3.0.1
  webview_flutter: ^2.0.4
  fluttertoast: ^7.1.6
  photo_view: ^0.10.3
  firebase_crashlytics: ^2.0.4
  sms_retriever:
    path: ./sms_retriever/
  wifi_info_flutter: ^2.0.2
  geolocator: ^7.7.1
  http: ^0.13.4
  contacts_service: ^0.6.1
  fluttercontactpicker: ^4.4.0
  flutter_device_type: ^0.4.0
  hawk_fab_menu: ^0.3.2
  youtube_player_flutter: ^8.0.0
  social_share_plugin: ^0.3.1+1
  slide_to_act: any
  connectivity_plus: ^1.0.6
  device_info: ^2.0.0
  cached_network_image: ^3.0.0
  sqflite: ^2.0.0+3
  flutter_linkify: ^5.0.2
  uni_links: ^0.5.1
  intl: ^0.17.0
  animated_text_kit: ^4.2.1
  shimmer: ^2.0.0
  lottie: ^1.1.0
  app_settings: ^4.1.1
  animations: ^2.0.1
  syncfusion_flutter_datepicker: ^19.2.59
  flutter_html: ^2.1.2
  percent_indicator: ^2.1.7+2
  firebase_in_app_messaging: ^0.5.0+10
  animated_bottom_navigation_bar: ^0.3.2
  search_choices: ^2.0.14
  easy_mask: ^2.0.1
  video_player: ^2.2.5
  better_player: ^0.0.77
  animate_icons: ^2.0.0
  timeline_tile: ^2.0.0
  avatar_glow: ^2.0.1
  vibration: ^1.7.4-nullsafety.0
  flutter_statusbarcolor_ns: ^0.4.0
  steel_crypt: ^3.0.0
  crypto: ^3.0.1

dev_dependencies:
  retrofit_generator: any
  build_runner: any
  json_serializable: any
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/cards/
    - assets/images/new_images/intro/
    - assets/images/new_images/
    - assets/images/new_images/dashboard/
    - assets/images/new_images/insurance/
    - assets/animation/
    - assets/db/
    - assets/images/login/
    - assets/images/new_images/wallet/
    - assets/images/new_images/profile_image/
    - assets/images/











































































    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/assets-and-images/#resolution-aware.

    # For details regarding adding assets from package dependencies, see
    # https://flutter.dev/assets-and-images/#from-packages

    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:
    # fonts:
    #   - family: Open Sans
    #     fonts:
    #       - asset: fonts/OpenSans-Regular.ttf


  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
